// Code generated by xgen. DO NOT EDIT.

package xml

// Valute ...
type Valute struct {
	IDAttr   string `xml:"ID,attr"`
	NumCode  uint16 `xml:"NumCode"`
	CharCode string `xml:"CharCode"`
	Nominal  uint32 `xml:"Nominal"`
	Name     string `xml:"Name"`
	Value    string `xml:"Value"`
}

// ValCurs ...
type ValCurs struct {
	DateAttr string    `xml:"Date,attr"`
	NameAttr string    `xml:"name,attr"`
	Valute   []*Valute `xml:"Valute"`
}
