package json

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
)

type AutoGenerated struct {
	XMLName struct {
		Space string `json:"Space"`
		Local string `json:"Local"`
	} `json:"xml_name"`
	Date   string `json:"date"`
	Name   string `json:"name"`
	Valute []struct {
		ID       string `json:"ID"`
		NumCode  string `json:"numCode"`
		CharCode string `json:"charCode"`
		Nominal  string `json:"nominal"`
		Name     string `json:"name"`
		Value    string `json:"value"`
	} `json:"Valute"`
}

var auto AutoGenerated

func DecodeFileJSON() {
	file, err := os.Open("C:/projects/exchange/decodedjson.json")
	if err != nil {
		log.Printf(err.Error())
	}
	defer file.Close()
	data, err := ioutil.ReadAll(file)

	if err != nil {
		log.Printf(err.Error())
	}

	jsonErr := json.Unmarshal(data, &auto)

	if jsonErr != nil {
		log.Printf(jsonErr.Error())
	}
	jsonData, _ := json.MarshalIndent(auto, "", " ")
	fmt.Println(string(jsonData))
}
